name: Check

on: pull_request

permissions:
  contents: read
  packages: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
          always-auth: true
          scope: "@saitamau-maximum"

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: .npmrc.pages

      - name: Lint Check
        run: pnpm check

      - name: Build Check
        run: pnpm build

      - name: Markdownlint Check
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"
